[project]
name = "g060525-e-pt"
version = "0.1.0"
description = "Система обработки презентаций"
requires-python = ">=3.11"
dependencies = [
    # Основные зависимости
    "python-pptx>=0.6.21",
    "tqdm>=4.62.2",
    "click>=8.0.1",
    "rich>=10.12.0",
]
